apiVersion: v1
kind: Service
metadata:
  name: sequencer
  labels:
    app: sequencer
spec:
  ports:
    - port: 12345
      name: grpc
    - port: 7000
      name: raft
  clusterIP: None
  selector:
    app: sequencer
