// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console2} from "forge-std/Test.sol";

/**
 * @title OrderVerifier
 * @dev Validates decrypted transaction data against the initial Go-layer commitment.
 * Ensures the sequencer didn't tamper with the order details after commitment.
 */
contract OrderVerifier {

    // Event emitted when an order is successfully verified
    event OrderVerified(bytes32 indexed commitment, string orderId);

    // Event emitted when verification fails
    event VerificationFailed(bytes32 indexed commitment, string orderId, string reason);

    // Store valid commitments (committed by the sequencer before decryption)
    mapping(bytes32 => bool) public validCommitments;

    /**
     * @dev Commits an order hash to the blockchain.
     * In a full implementation, this would be part of a Merkle root commitment
     * representing the entire batch of FIFO-ordered transactions.
     * @param commitment The SHA-256 hash generated by the Go layer.
     */
    function commitOrder(bytes32 commitment) external {
        validCommitments[commitment] = true;
    }

    struct OrderData {
        string orderId;
        string user;
        string token;
        string amountStr;
        string priceStr;
        string timestampStr;
        string nonce;
    }

    /**
     * @dev Verifies that the decrypted order details match the stored commitment.
     * The parameters should be pre-formatted as strings to match the Go layer's
     * pipe-delimited canonical format: "%s|%s|%s|%f|%f|%d|%s"
     */
    function verifyOrder(OrderData calldata order) external returns (bool) {
        // Reconstruct the Go-layer pipe-delimited canonical string:
        // "OrderID|User|Token|Amount|Price|Timestamp|Nonce"
        bytes memory p1 = abi.encodePacked(order.orderId, "|", order.user, "|", order.token, "|", order.amountStr);
        bytes memory p2 = abi.encodePacked("|", order.priceStr, "|", order.timestampStr, "|", order.nonce);

        // Compute the SHA-256 hash of the payload
        // This matches Go's crypto/sha256 implementation
        bytes32 generatedCommitment = sha256(abi.encodePacked(p1, p2));

        // Check if the commitment was previously registered
        if (!validCommitments[generatedCommitment]) {
            emit VerificationFailed(generatedCommitment, order.orderId, "Commitment not found or mismatched");
            return false;
        }

        // Verification successful
        // In a real system, the trade would now be executed on the DEX

        // Prevent replay of the same order verification
        validCommitments[generatedCommitment] = false;

        emit OrderVerified(generatedCommitment, order.orderId);
        return true;
    }
}

contract OrderVerifierTest is Test {
    OrderVerifier public verifier;

    // Valid order components (simulating the Go layer formatting)
    string constant orderId = "12345";
    string constant user = "0xABCDEF";
    string constant token = "ETH";
    string constant amountStr = "2.500000";
    string constant priceStr = "1800.000000";
    string constant timestampStr = "1700000000";
    string constant nonce = "random123";

    bytes32 validCommitment;

    // Events to test for
    event OrderVerified(bytes32 indexed commitment, string orderId);
    event VerificationFailed(bytes32 indexed commitment, string orderId, string reason);

    function setUp() public {
        verifier = new OrderVerifier();

        // Reconstruct the Go-layer pipe-delimited canonical string to compute the expected hash
        bytes memory payload = abi.encodePacked(
            orderId, "|",
            user, "|",
            token, "|",
            amountStr, "|",
            priceStr, "|",
            timestampStr, "|",
            nonce
        );
        validCommitment = sha256(payload);
    }

    function test_SuccessfulVerification() public {
        // 1. Sequencer commits the hash on-chain
        verifier.commitOrder(validCommitment);
        assertTrue(verifier.validCommitments(validCommitment), "Commitment should be stored");

        // 2. Expect the OrderVerified event
        vm.expectEmit(true, false, false, true);
        emit OrderVerified(validCommitment, orderId);

        // 3. User or system provides the decrypted data
        OrderVerifier.OrderData memory order = OrderVerifier.OrderData(
            orderId, user, token, amountStr, priceStr, timestampStr, nonce
        );
        bool success = verifier.verifyOrder(order);

        // 4. Assertions
        assertTrue(success, "Verification should succeed with untampered data");
        assertFalse(verifier.validCommitments(validCommitment), "Commitment should be cleared to prevent replays");
    }

    function test_TamperedDataFails() public {
        // 1. Sequencer commits the original hash on-chain
        verifier.commitOrder(validCommitment);

        // 2. An attacker tries to submit tampered data (e.g., changed price)
        string memory tamperedPrice = "1900.000000";

        bytes memory tamperedPayload = abi.encodePacked(
            orderId, "|", user, "|", token, "|", amountStr, "|",
            tamperedPrice, "|", timestampStr, "|", nonce
        );
        bytes32 tamperedCommitment = sha256(tamperedPayload);

        // 3. Expect the VerificationFailed event
        vm.expectEmit(true, false, false, true);
        emit VerificationFailed(tamperedCommitment, orderId, "Commitment not found or mismatched");

        // 4. Call verifyOrder with the tampered price
        OrderVerifier.OrderData memory tamperedOrder = OrderVerifier.OrderData(
            orderId, user, token, amountStr, tamperedPrice, timestampStr, nonce
        );
        bool success = verifier.verifyOrder(tamperedOrder);

        // 5. Assertions
        assertFalse(success, "Verification should fail for tampered data");
        assertTrue(verifier.validCommitments(validCommitment), "Original commitment should remain untouched");
    }

    function test_UncommittedOrderFails() public {
        // 1. Do NOT call commitOrder, meaning the system hasn't seen this order yet

        // 2. Call verifyOrder
        OrderVerifier.OrderData memory order = OrderVerifier.OrderData(
            orderId, user, token, amountStr, priceStr, timestampStr, nonce
        );
        bool success = verifier.verifyOrder(order);

        // 3. Assertions
        assertFalse(success, "Verification should fail if the hash was never committed");
    }

    function test_ReplayProtection() public {
        // 1. Sequencer commits the hash
        verifier.commitOrder(validCommitment);

        OrderVerifier.OrderData memory order = OrderVerifier.OrderData(
            orderId, user, token, amountStr, priceStr, timestampStr, nonce
        );

        // 2. First verification should succeed
        bool firstSuccess = verifier.verifyOrder(order);
        assertTrue(firstSuccess, "First verification should succeed");

        // 3. Second verification of the exact same data should fail
        bool secondSuccess = verifier.verifyOrder(order);
        assertFalse(secondSuccess, "Second verification should fail due to replay protection");
    }
}
